### ISSUE TITLE
Compare different methods of creating low-LOD versions of 3D DOs

### ISSUE THREAD

**Issue by andreasbueckle** [cns-iu/hra-organ-gallery-in-vr#241]
We want to compare frame rates, anatomical correctness, and aesthetics for two types of low-LOD models: created by @LuchenCatherine via CGAL at https://github.com/LuchenCatherine/multi-LOD/tree/main (**Alg LOD**), and by @u-p-design via Cinema 4D at https://github.com/cns-iu/hra-organ-gallery-assets (**C4D LOD**).

 Collectively, all 3D Reference Objects have 8,169,482 million triangles. Procedurally generated level-of-detail (LOD) variations allow for faster use in web browsers and on lower-tier immersive virtual reality (VR) hardware. For example, the highest-LOD version of the female, left eye has 346,630 triangles, whereas a version with 80% fewer vertices has just 195,393 triangles. Meta recommends 750k-1M for the Quest 2: [https://developer.oculus.com/documentation/unity/unity-perf/#performance-targets](https://www.google.com/url?q=https://developer.oculus.com/documentation/unity/unity-perf/%23performance-targets&sa=D&source=docs&ust=1692898527173398&usg=AOvVaw0epdXZ92WRvvwY2yQhs-kj). Need 88 percent reduction!

# TODOs:
- [x] #184 
- [x] Have @u-p-design create 2-3 low-res versions of heart as C4D LODs
- [x] Compare initial C4D LODs for heart with @LuchenCatherine's Alg LODs. Needed only if changes are made. Once time computation, forever usage.
- [ ] Conduct later testing if needed

# **Success criteria**: 
- @u-p-design  and @HeidiS25 OK the low-LOD models (made with algorithm ["Alg"] or Cinema 4D ["C4D"]) for anatomical correctness for heart. 
- When any single, any combination of, or all organs are within user's view port, the frame rate does no go below 60 fps (Meta suggests 72 fps but that is the max the Meta Quest 2 can do). 

Need optimum between performance (frame rate), anatomical accuracy, and aesthetics (if organ position relative to origin is preserved):

# Output
Need table that compares:
- Frame rate
- Aesthetics
- Heidi's and Ushma's judgement an anatomical accuracy

For
- GLB
- Alg LOD
- C4D LOD

## Test for 1 organ (@thespiritninja)
- [x] Create new Unity project in https://github.com/cns-iu/hra-organ-gallery-assets
- [x] Put all hearts into one VR scene: 
- HRA v1.4 VHF heart (get from https://github.com/hubmapconsortium/ccf-3d-reference-object-library)
- Alg LOD 0.8
- Alg LOD 0.6
- Alg LOD 0.4
- Alg LOD 0.2
- C4D LOD 0.8
- C4D LOD 0.6
- C4D LOD 0.4
- C4D LOD 0.2

- [x] Display frame rate
- [x] Add check boxes ```approved``` vs ```not_approved``` and labels for all with LOD number
- [x] Share in VR with @u-p-design and @HeidiS25 to assess anatomical correctness. 
- [x] Compile instructions on how to screen-record video and audio on Meta Quest 2
- [x] Share results with @andreasbueckle 

## **Later**: Test all Alg LOD organs
- [x] Put all Alg LOD organs into one VR scene
- [x] Add a filter to toggle organs on/off (no M/F, L/R)
- [x] Check frame rate on display only at first
- [x] Implement TaskManager and user button
- [x] Implement ```Logger.cs``` and record frame rate. 
- [x] Share results with @andreasbueckle

## **Later/if needed**: Test for all organs
1. If both low-LOD methods pass test 1, create a low-LOD version for each organ for 4 size steps (0.8 to 0.2) using C4D. 
2. For each method, place all organs into one VR scene to form one full body as will be shown in screenshot below.
3. Record frame rate and analyze. 

Steps if no satisfying solution is reached then:
- If does not work, make 0.1 LOD
- Then remove AS, e.g., in eye, too many AS that will be invisible
- Remove some AS because they will not be seen?
- Use hi-res skin, achieve lower sizer through what’s in the middle of the body
- Use occluding filters!

Notes:
- VHF heart: GLB is 3.9 MB
- Alg LOD 0.2 is ~700 KB
- Alg LOD 0.8 is 3.2 MB
- Alg LOD Eye had holes but not an issue for display

New HRA Organ Gallery main scene, with full-res HRA v1.4 organs: 
![image](https://github.com/cns-iu/hra-organ-gallery-in-vr/assets/22821046/f136d3bd-dc82-4240-9cb7-1f0060c7af74)

Comparison of HRA v1.2 heart, Alg LOD 0.6, and Alg LOD 0.2: 
![2023-08-02_09-54-56](https://github.com/cns-iu/hra-organ-gallery-in-vr/assets/22821046/e2b5df8d-6332-4df6-bb33-34539e195b7c)

**Comment by andreasbueckle** [comment]
@u-p-design uploads to https://github.com/cns-iu/hra-organ-gallery-assets

**Comment by andreasbueckle** [comment]
@u-p-design shares lower-poly version of keyboard.

**Comment by andreasbueckle** [comment]
Need:
- new scene in https://github.com/cns-iu/hra-organ-gallery-assets with FPS counter and logger to CSV or JSON
- Full Alg LOD body

**Comment by andreasbueckle** [comment]
@u-p-design shares C4D LOD 0.6 and modified keyboard
